name: Firefox Proxy
version: "1.2.0"
slug: firefox-proxy
init: false
panel_icon: mdi:web
panel_title: Firefox
panel_admin: true
ingress: true
hassio_api: true
description: Proxy for Firefox Docker container
boot: auto
arch: 
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
options:
    server_container_name: firefox
    server_port: 5800
    is_secured: false
schema:
    server_container_name: str
    server_port: int
    is_secured: bool